### 获取华为云token
POST https://iam.cn-north-4.myhuaweicloud.com/v3/auth/tokens
Content-Type: application/json

{
  "auth": {
    "identity": {
      "methods": [
        "password"
      ],
      "password": {
        "user": {
          "name": "xiongqiang333",
          "password": "password",
          "domain": {
            "name": "xiongqiang333"
          }
        }
      }
    }

  }
}

> {% client.global.set("token", response.headers.valueOf("X-Subject-Token")) %}

###
GET https://iotda.cn-north-4.myhuaweicloud.com/v5/iot/123/devices
x-auth-token: {{token}}

###
GET https://iotda.cn-north-4.myhuaweicloud.com/v5/iot/123/devices/605867618054bc02d86e3d8a_device_1617262045468
x-auth-token: {{token}}

